<div class="hero-unit">
    <h1><?php echo $this->helloPizza(); ?></h1>
</div>
<div class="row">
<?php foreach ($this->pizzaList as $pizza) : ?>
    <?php $url = $this->url('pizza-name', array('name' => $pizza)); ?>
    <div class="span3">
        <p>
            <a class="btn btn-primary" href="<?php echo $url; ?>">Pizza <?php echo $pizza; ?></a>
        </p>
    </div>
<?php endforeach; ?>
</div>
